import csv
import html
from collections.abc import Iterable
from dataclasses import dataclass
from html.parser import HTMLParser
from io import StringIO
from xml.sax.saxutils import escape

from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.db import transaction

from .models import User
from .services import user_create, user_update

IMPORT_HEADERS = (
    "email",
    "phone",
    "employee_id",
    "profile_name",
    "is_staff",
    "is_active",
    "password",
)
EXPORT_HEADERS = IMPORT_HEADERS
MAX_IMPORT_ROWS = 1000


@dataclass(frozen=True)
class UserImportResult:
    created: int
    updated: int


class _TableParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows: list[list[str]] = []
        self._row: list[str] | None = None
        self._cell: list[str] | None = None

    def handle_starttag(self, tag, attrs):
        if tag == "tr":
            self._row = []
        elif tag in {"td", "th"} and self._row is not None:
            self._cell = []

    def handle_endtag(self, tag):
        if tag in {"td", "th"} and self._row is not None and self._cell is not None:
            self._row.append(html.unescape("".join(self._cell)).strip())
            self._cell = None
        elif tag == "tr" and self._row is not None:
            if self._row:
                self.rows.append(self._row)
            self._row = None

    def handle_data(self, data):
        if self._cell is not None:
            self._cell.append(data)


def _rows_from_xls(content: bytes) -> list[list[str]]:
    parser = _TableParser()
    parser.feed(content.decode("utf-8-sig"))
    if not parser.rows:
        raise ValueError("The XLS file must be an Excel-compatible table export.")
    return parser.rows


def _rows_from_upload(upload) -> list[list[str]]:
    if upload.size > 5 * 1024 * 1024:
        raise ValueError("Import file must be 5 MB or smaller.")
    content = upload.read()
    suffix = upload.name.lower().rsplit(".", 1)[-1] if "." in upload.name else ""
    if suffix == "csv":
        try:
            return list(csv.reader(StringIO(content.decode("utf-8-sig"))))
        except (UnicodeDecodeError, csv.Error) as error:
            raise ValueError("CSV file is malformed or must use UTF-8 encoding.") from error
    if suffix == "xls":
        try:
            return _rows_from_xls(content)
        except UnicodeDecodeError as error:
            raise ValueError(
                "XLS must be an Excel-compatible table export generated by the template."
            ) from error
    raise ValueError("Only CSV and XLS files are supported.")


def _boolean(value: str, field: str, row_number: int) -> bool:
    normalized = value.strip().lower()
    if normalized in {"true", "1", "yes", "y"}:
        return True
    if normalized in {"false", "0", "no", "n"}:
        return False
    raise ValueError(f"Row {row_number}: {field} must be true or false.")


def _normalized_records(rows: list[list[str]]) -> list[dict[str, str]]:
    if not rows:
        raise ValueError("The import file is empty.")
    headers = tuple(value.strip().lower() for value in rows[0])
    if headers != IMPORT_HEADERS:
        raise ValueError("The header must be: " + ", ".join(IMPORT_HEADERS))
    records = []
    for row_number, values in enumerate(rows[1:], start=2):
        if not any(value.strip() for value in values):
            continue
        if len(values) != len(IMPORT_HEADERS):
            raise ValueError(f"Row {row_number}: expected {len(IMPORT_HEADERS)} columns.")
        records.append(
            dict(zip(IMPORT_HEADERS, (value.strip() for value in values), strict=True))
        )
    if not records:
        raise ValueError("The import file contains no user rows.")
    if len(records) > MAX_IMPORT_ROWS:
        raise ValueError(f"Import is limited to {MAX_IMPORT_ROWS} users per file.")
    return records


def _validate_records(records: Iterable[dict[str, str]]) -> list[dict[str, str | bool]]:
    validated: list[dict[str, str | bool]] = []
    emails: set[str] = set()
    phones: set[str] = set()
    employee_ids: set[str] = set()
    for row_number, record in enumerate(records, start=2):
        email = record["email"].lower()
        if not email:
            raise ValueError(f"Row {row_number}: email is required.")
        try:
            validate_email(email)
        except ValidationError as error:
            raise ValueError(f"Row {row_number}: email is invalid.") from error
        if email in emails:
            raise ValueError(f"Row {row_number}: email is duplicated in the file.")
        emails.add(email)
        phone = record["phone"]
        employee_id = record["employee_id"]
        profile_name = record["profile_name"]
        if len(phone) > 20:
            raise ValueError(f"Row {row_number}: phone must be 20 characters or fewer.")
        if len(employee_id) > 50:
            raise ValueError(
                f"Row {row_number}: employee_id must be 50 characters or fewer."
            )
        if len(profile_name) > 150:
            raise ValueError(
                f"Row {row_number}: profile_name must be 150 characters or fewer."
            )
        if phone:
            if phone in phones:
                raise ValueError(f"Row {row_number}: phone is duplicated in the file.")
            if User.objects.filter(phone=phone).exclude(email=email).exists():
                raise ValueError(f"Row {row_number}: phone already belongs to another user.")
            phones.add(phone)
        if employee_id:
            if employee_id in employee_ids:
                raise ValueError(
                    f"Row {row_number}: employee_id is duplicated in the file."
                )
            if User.objects.filter(employee_id=employee_id).exclude(email=email).exists():
                raise ValueError(
                    f"Row {row_number}: employee_id already belongs to another user."
                )
            employee_ids.add(employee_id)
        validated.append(
            {
                **record,
                "email": email,
                "is_staff": _boolean(record["is_staff"], "is_staff", row_number),
                "is_active": _boolean(record["is_active"], "is_active", row_number),
            }
        )
    return validated


@transaction.atomic
def import_users(*, upload) -> UserImportResult:
    records = _validate_records(_normalized_records(_rows_from_upload(upload)))
    created = updated = 0
    for record in records:
        email = str(record["email"])
        user = User.objects.filter(email=email).first()
        if user is None:
            password = str(record["password"])
            if len(password) < 8:
                raise ValueError(f"User {email}: password is required and must be 8+ characters.")
            user_create(
                email=email,
                phone=str(record["phone"]) or None,
                employee_id=str(record["employee_id"]) or None,
                is_staff=bool(record["is_staff"]),
                is_active=bool(record["is_active"]),
                profile_name=str(record["profile_name"]),
                password=password,
            )
            created += 1
            continue
        password = str(record["password"])
        if password and len(password) < 8:
            raise ValueError(f"User {email}: password must be 8+ characters.")
        user_update(
            user=user,
            phone=str(record["phone"]) or None,
            employee_id=str(record["employee_id"]) or None,
            profile_name=str(record["profile_name"]),
            is_staff=bool(record["is_staff"]),
            is_active=bool(record["is_active"]),
            password=password or None,
        )
        updated += 1
    return UserImportResult(created=created, updated=updated)


def user_export_rows(users: Iterable[User]) -> list[list[str]]:
    def safe(value: str) -> str:
        return "'" + value if value.startswith(("=", "+", "-", "@")) else value

    return [
        list(EXPORT_HEADERS),
        *[
            [
                safe(user.email),
                safe(user.phone or ""),
                safe(user.employee_id or ""),
                safe(user.profile_name),
                safe(str(user.is_staff).lower()),
                safe(str(user.is_active).lower()),
                "",
            ]
            for user in users
        ],
    ]


def csv_bytes(rows: list[list[str]]) -> bytes:
    output = StringIO(newline="")
    csv.writer(output).writerows(rows)
    return output.getvalue().encode("utf-8-sig")


def xls_bytes(rows: list[list[str]]) -> bytes:
    body = "".join(
        "<tr>" + "".join(f"<td>{escape(str(value))}</td>" for value in row) + "</tr>"
        for row in rows
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<!DOCTYPE html><html><head><meta charset="UTF-8"></head>'
        f"<body><table>{body}</table></body></html>"
    ).encode()
