# Generated by Django 6.1 on 2026-08-11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuntimeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("task_result_id", models.CharField(max_length=64, unique=True)),
                ("task_name", models.CharField(max_length=255)),
                ("backend", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_class", models.CharField(blank=True, max_length=255)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="runtimelog",
            index=models.Index(
                fields=["status", "-created"], name="platform_ru_status_2da504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runtimelog",
            index=models.Index(
                fields=["task_name", "-created"], name="platform_ru_task_na_20d248_idx"
            ),
        ),
    ]
