# Generated by Django 6.1 on 2026-08-11 09:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0003_runtime_log_dashboard_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=150)),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_reference', models.CharField(max_length=80)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('enqueued', 'Enqueued'), ('processed', 'Processed'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='received', max_length=20)),
                ('task_result_id', models.CharField(blank=True, max_length=64)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'external_event_id'], name='platform_ru_provide_8dc81b_idx'), models.Index(fields=['status', '-received_at'], name='platform_ru_status_2ec412_idx')],
            },
        ),
    ]
