# Generated by Django 6.1 on 2026-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0004_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='safe_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
