# Generated by Django 6.1 on 2026-08-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0005_webhookevent_safe_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='replay_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='platform_runtime.webhookevent'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('enqueued', 'Enqueued'), ('processed', 'Processed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('replayed', 'Replayed')], db_index=True, default='received', max_length=20),
        ),
    ]
