# Generated by Django 6.1 on 2026-08-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0006_webhookevent_replay_of_alter_webhookevent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevent',
            name='replay_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay', to='platform_runtime.webhookevent'),
        ),
    ]
