# Generated by Django 6.1 on 2026-08-11 09:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0007_alter_webhookevent_replay_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=150)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('safe_payload', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['event_type', '-published_at'], name='platform_ru_event_t_497439_idx')],
            },
        ),
    ]
