# Generated by Django 6.1 on 2026-08-11 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_runtime', '0008_realtimeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeevent',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='realtimeevent',
            index=models.Index(fields=['expires_at', '-published_at'], name='platform_ru_expires_7ff391_idx'),
        ),
    ]
